### ISSUE TITLE
MySQLCursorPrepared doesn't work with pyformat placeholder

### ISSUE THREAD

**Issue by sgykfjsm** [pingcap/tidb-course-201-lab#13]
When I tried `10-demo-python-prepared-statement-01-lastrowid-show.sh`, I got the following exception error.

```console
$ bash ./10-demo-python-prepared-statement-01-lastrowid-show.sh
Traceback (most recent call last):
  File "/private/tmp/tidb-course-201-lab/scripts/venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 523, in cmd_stmt_prepare
    stmt = self._cmysql.stmt_prepare(statement)
_mysql_connector.MySQLInterfaceError: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 31 near "%(name)s)"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/private/tmp/tidb-course-201-lab/scripts/./DemoPythonPreparedStatementLastrowid.py", line 16, in <module>
    cursor.execute(query_insert, ({"name": "ABC"}))
  File "/private/tmp/tidb-course-201-lab/scripts/venv/lib/python3.10/site-packages/mysql/connector/cursor_cext.py", line 1072, in execute
    self._stmt = self._cnx.cmd_stmt_prepare(operation)
  File "/private/tmp/tidb-course-201-lab/scripts/venv/lib/python3.10/site-packages/mysql/connector/connection_cext.py", line 527, in cmd_stmt_prepare
    raise InterfaceError(str(err)) from err
mysql.connector.errors.InterfaceError: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 31 near "%(name)s)"
```

The document https://dev.mysql.com/doc/connector-python/en/connector-python-api-mysqlcursorprepared.html says:
> Prepared statements executed with MySQLCursorPrepared can use the format (%s) or qmark (?) parameterization style. This differs from nonprepared statements executed with MySQLCursor, which can use the format or pyformat parameterization style.

So, if the code "DemoPythonPreparedStatementLastrowid.py" is modified like this, it works.
```python
# query_insert = "INSERT INTO t2 (name) VALUES (%(name)s)"
query_insert = "INSERT INTO t2 (name) VALUES (%s)"
cursor.execute(query_setup)
# cursor.execute(query_insert, ({"name": "ABC"}))
cursor.execute(query_insert, ("ABC",))
print("Generated PK is", cursor.lastrowid)
```

My environment is as below:
```console
$ sw_vers
ProductName:    macOS
ProductVersion: 12.6
BuildVersion:   21G115

$ python -V
Python 3.10.5

$ pip freeze
mysql-connector==2.2.9
mysql-connector-python==8.0.31
protobuf==3.20.1
```
TiDB version is v6.3.0.

**Comment by guangleibao** [comment]
Fixed.

`DemoPythonPreparedStatementLastrowid.py` modified to use the placeholder style. `10-demo-python-prepared-statement-01-lastrowid-show.sh` is also modified to install the `connector` and `connector-python` modules to make this demo more self-descriptive.
